money_start = input('Enter inital savings: $')
saving_years = input('Enter whole years of savings: ')
interest_rate = input('Enter interest rate %: ')
money_result = float(money_start)*(float(interest_rate)/100)*int(saving_years)
print (f"Savings simple interest: ${money_result}")
print (f"Savings simple interest greater than 10000: {money_result > 10000}")
principle_interest = float(money_start)+float(money_result)
print (f"Principle and Interest is: ${principle_interest}")
print (f"Principle and interest greater than 10000: {principle_interest > 10000}")
